"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import { AuthContextProvider } from "./context/AuthContext";
import MenuBar from "./components/MenuBar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUIProvider>
          <main className="dark text-foreground bg-background">
            <AuthContextProvider>
              <MenuBar />
              {children}
            </AuthContextProvider>
          </main>
        </NextUIProvider>
      </body>
    </html>
  );
}
